// THERE IS A DIFFERENCE BETWEEN SUBSEQUENCE AND SUBSTRING
// SUBSTRING : FOR (abc) : contiguous, and ordered: a,b,c,ab,abc,bc, (blank)
//  SUBSEQUENCE : IT DOES TAKES INTO ACCOUNT THE ORDER, BUT THE ANS NEED NOT BE CONTIGUOUS : a,b,c,ab,abc,bc, (blank), ac*
// PERMUTATIONS : IT NEEDS TO HAVE ALL THE CHARACTERS INCLUDED, JUST THAT ARRANGED IN ALL POSSIBLE COMBINATIONS : abc,acb, bca,bac, cab,cba
